[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[env]
term = "xterm-256color"

[window]
dynamic_padding = true
option_as_alt = "Both"

[font]
size = 14
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"
